#spring.devtools.add-properties:false

auth:
  pocket:
    url:
      request: https://getpocket.com/v3/oauth/request
      authorize: https://getpocket.com/v3/oauth/authorize
      get: https://getpocket.com/v3/get
    consumer-key: ${POCKET_CONSUMER_KEY}
    redirect_uri: http://localhost:8080/pocket/auth/token

shell.out.info: CYAN
shell.out.success: GREEN
shell.out.warning: YELLOW
shell.out.error: RED

management:
  endpoints:
    web:
      exposure:
        include: [ 'configprops', 'mappings', 'health', 'info', 'logfile', 'loggers', 'endpoints' ]