#spring.devtools.add-properties:false

logging:
  level:
    eu.cybershu: DEBUG

auth:
  pocket:
    url:
      request: https://getpocket.com/v3/oauth/request
      authorize_app: https://getpocket.com/auth/authorize
      access_token: https://getpocket.com/v3/oauth/authorize
      get: https://getpocket.com/v3/get
    consumer-key: ${POCKET_CONSUMER_KEY}
    redirect_uri: ${VUE_APP_BACKEND_URL:http://localhost:8081}/pocket/auth/token

management:
  endpoints:
    web:
      exposure:
        include: [ 'configprops', 'mappings', 'health', 'info', 'logfile', 'loggers', 'endpoints' ]
server:
  port: ${PORT:8081}
  error:
    include-binding-errors: always

spring:
  server:
    port: ${PORT:8081}
    servlet:
      context-path: /pocketstats
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  datasource.driver-class-name: com.mysql.jdbc.Driver
  data:
    mongodb:
      authentication-database: admin
      auto-index-creation: true
      database: ${MONGODB_DB:db}
      uri: ${MONGODB_URI}