logging:
  level:
    eu.cybershu: INFO

auth:
  pocket:
    redirect_uri: ${BACKEND_URL}/pocket/auth/token

management:
  endpoints:
    web:
      exposure:
        include: [ 'health', 'info' ]

spring:
  server:
    port: ${PORT:8081}
    servlet:
      context-path: /