spring:
  data:
    mongodb:
      username: ${MONGODB_USER:admin}
      password: ${MONGODB_PASS:admin}
      database: ${MONGODB_DB:db}
      authentication-database: admin
      auto-index-creation: true
      host: ${MONGODB_HOST:localhost}
      port: ${MONGODB_PORT:27017}