name: PocketStats CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Official SonarQube Scan
      # You may pin to the exact commit or the version.
      # uses: SonarSource/sonarqube-scan-action@a6ba0aafc293e03de5437af7edbc97f7d3ebc91a
      uses: SonarSource/sonarqube-scan-action@v1.2.0
      with:
        # Additional arguments to the sonar-scanner
        # Set the sonar.projectBaseDir analysis property
        projectBaseDir: .

    - name: Set up Java
      uses: actions/setup-java@v3.9.0
      with:
        distribution: 'temurin'
        java-version: '17'
        check-latest: true

    - name: Backend tests
      working-directory: backend
      run: ../gradlew test

    - name: Build backend
      working-directory: backend
      run: ../gradlew build

    - name: Build frontend
      working-directory: frontend
      run: npm install && npm run build
