name: PocketStats CI

on: [push, pull_request]

jobs:
#   static-analysis:
#    runs-on: ubuntu-latest
#    name: "SonarScan analysis"

#    steps:
#     - name: Checkout code
#       uses: actions/checkout@v2
#     - name: Set up Java
#       uses: actions/setup-java@v3.9.0
#       with:
#         distribution: 'temurin'
#         java-version: '17'
#         check-latest: true
#     - name: Analyze with SonarCloud
#       uses: sonarsource/sonarcloud-github-action@master
#       env:
#           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
#       with:
#         args: >
#           -Dsonar.organization=michmzr
#           -Dsonar.projectKey=michmzr_PocketStats
#           -Dsonar.host.url=https://sonarcloud.io
#           -Dsonar.verbose=true
#     - name: Cache Gradle packages
#       uses: actions/cache@v1
#       with:
#         path: ~/.gradle/caches
#         key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
#         restore-keys: ${{ runner.os }}-gradle
#     - name: Build and analyze
#       run: ./gradlew build jacocoTestReport sonar --info   -Dsonar.organization=michmzr  -Dsonar.projectKey=michmzr_PocketStats  -Dsonar.host.url=https://sonarcloud.io  -Dsonar.verbose=true
#       env:
#         # SonarCloud access token should be generated from https://sonarcloud.io/account/security/
#         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
       
  tests:
    runs-on: ubuntu-latest
    environment: master
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Java
        uses: actions/setup-java@v3.9.0
        with:
          distribution: 'temurin'
          java-version: '17'
          check-latest: true

      - name: Backend tests
        working-directory: backend
        run: ../gradlew test
  build:
    #    needs:
    #      - tests
    runs-on: ubuntu-latest
    environment: master
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Java
        uses: actions/setup-java@v3.9.0
        with:
          distribution: 'temurin'
          java-version: '17'
          check-latest: false #todo set true
      - uses: gradle/gradle-build-action@v2.4.0
        with:
           gradle-version: current
           arguments: shadowJar -x test
#       - name: Build backend
#         working-directory: backend
#         run: ../gradlew build --debug
      #      - name: Build frontend
      #        working-directory: frontend
      #        run: npm install && npm run build
      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
      - id: 'deploy'
        uses: 'google-github-actions/deploy-appengine@v1'
        with:
          deliverables: app.yaml
          deployables: ./backend/build/libs/*.jar
          env_vars: |-
            FOO=bar
            ZIP=zap
      - id: 'test'
        run: 'curl "${{ steps.deploy.outputs.url }}"'
#      - name: Deploy to Google Cloud App Engine
#        run: |
#          gcloud app deploy --quiet --project ${{ secrets.GCP_PROJECT_ID }} ./backend/build/libs/*.jar  --log-http --verbosity=debug