name: PocketStats CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v3.9.0
      with:
        distribution: 'temurin'
        java-version: '17'
        check-latest: true

    - name: Backend tests
      working-directory: backend
      run: ../gradlew test

    - name: Build backend
      working-directory: backend
      run: ../gradlew build

    - name: Build frontend
      working-directory: frontend
      run: npm install && npm run build
